routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
    Route::get('/', 'MainController@home');
    Route::get('client-register', 'AuthController@register');
    Route::get('about', 'MainController@about');
    Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth'] , 'prefix'=>'admin'],function() {
    Route::get('home', 'HomeController@index');
    Route::resource('governorates','GovernorateController');
    Route::resource('cities','CityController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('donations','DonationController');
    Route::resource('contacts','ContactController');
    Route::resource('reports','ReportController');
    Route::get('clients-activate/{id}','ClientController@activate')->name('clients.activate');
    Route::get('clients-deactivate/{id}','ClientController@deactivate')->name('clients.deactivate');
    Route::get('clients-toggle-activation/{id}','ClientController@toggleActivation')->name('clients.toggle-activation');
    Route::resource('clients','ClientController');
    Route::resource('settings','SettingController');
    Route::resource('user','UserController');
    Route::resource('role','RoleController');
    // User reset password
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');

});

app/Http/Controllers/DonationController.php
<?php

namespace App\Http\Controllers;

use App\Models\BloodType;
use App\Models\City;
use App\Models\DonationRequest;
use Illuminate\Http\Request;

class DonationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $records = DonationRequest::paginate(20);
        return view('donations.index', compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bloodtypes = BloodType::pluck('name', 'id')->toArray();
        $cities = City::pluck('name', 'id')->toArray();
        return view('donations.create', compact('bloodtypes', 'cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bloodtypes = BloodType::pluck('name', 'id')->toArray();
        $cities = City::pluck('name', 'id')->toArray();
        $model = DonationRequest::findOrFail($id);
        return view('donations.edit', compact('model', 'bloodtypes', 'cities'));
    }


    public function update(Request $request, $id)
    {
        $rules = [
            'patient_name'     => 'required',
            'patient_age'      => 'required',
            'hospital_name'    => 'required',
            'hospital_address' => 'required',
            'blood_bags'       => 'required',
            'phone'            => 'required',
            'blood_type_id'    => 'required',
            'city_id'          => 'required',
            'notes'            => 'required',
        ];
        $this->validate($request, $rules);
        $record = DonationRequest::findOrFail($id);
        $record->update($request->all());
        flash()->success('تــم التحديث');
        return redirect(route('donations.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = DonationRequest::find($id);
        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        $record->delete();
        return response()->json([
                'status'  => 1,
                'message' => 'تم الحذف بنجاح',
                'id'      => $id
            ]);
    }

}

resources/views/donations/edit.blade.php
@extends('layouts.app')
@section('page_title')
   تعديل التبرع
@endsection

@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                @include('partials.validation_errors')
                {!! Form::model($model,[
                'action' => ['DonationController@update',$model->id],
                'method' =>'put'
                ]) !!}
                <div class="form-group">
                    <label for="patient_name">اسم المريض</label>
                    {!! Form::text('patient_name',null,[
                        'class'=>'form-control'
                    ]) !!}
                </div>
                <div class="form-group">
                    <label for="patient_age">العمر</label>
                    {!! Form::number('patient_age',null,[
                        'class'=>'form-control'
                    ]) !!}
                </div>

                <div class="form-group">
                    <label for="phone">الهاتف</label>
                    {!! Form::text('phone',null,[
                        'class'=>'form-control'
                    ]) !!}

                    <div class="form-group">
                        <label for="hospital_name">اسم المستشفى</label>
                        {!! Form::text('hospital_name',null,[
                            'class'=>'form-control'
                        ]) !!}
                    </div>

                    <div class="form-group">
                        <label for="hospital_address">عنوان المستشفى</label>
                        {!! Form::text('hospital_address',null,[
                            'class'=>'form-control'
                        ]) !!}
                    </div>
                    <div class="form-group">
                        <label for="notes">ملاحظات</label>
                        {!! Form::textarea('notes',null,[
                            'class'=>'form-control'
                        ]) !!}
                    </div>
                    <div class="form-group">
                        <label for="blood_bags">أكياس الدم</label>
                        {!! Form::number('bags_num',null,[
                            'class'=>'form-control'
                        ]) !!}
                    </div>

                    <div class="form-group">
                        <label for="blood_type">فصيلة الدم</label>
                        {!! Form::select('blood_type_id',$bloodtypes,[],[
                            'class'=>'form-control'
                        ]) !!}
                    </div>

                    <div class="form-group">
                        <label for="city">المدينة</label>
                        {!! Form::select('city_id',$cities,[],[
                            'class'=>'form-control'
                        ]) !!}
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="submit"> تحديث</button>
                    </div>
                </div>


                {!! Form::close () !!}
            </div>

        </div>
    </section>
@endsection

resources/views/donations/index.blade.php
@extends('layouts.app')
@inject('donation','App\Models\DonationRequest')
@section('page_title')
    التبرعات
@endsection

@section('content')


    <section class="content">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">كل التبرعات</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">

                @include('flash::message')
                @if(count($records))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>اسم المريض</th>
                                <th>العمر</th>
                                <th>عدد أكياس الدم</th>
                                <th>اسم المستشفى</th>
                                <th>عنوان المستشفى</th>
                                <th>الهاتف</th>
                                <th>المدينة</th>
                                <th>فصيلة الدم</th>
                                <th class="text-center">تعديل</th>
                                <th class="text-center">حذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr id="removable{{$record->id}}">
                                    <td class="text-center">{{$loop->iteration}}</td>
                                    <td class="text-center">{{$record->patient_name}}</td>
                                    <td class="text-center">{{$record->patient_age}}</td>
                                    <td class="text-center">{{$record->bags_num}}</td>
                                    <td class="text-center">{{$record->hospital_name}}</td>
                                    <td class="text-center">{{$record->hospital_address}}</td>
                                    <td class="text-center">{{$record->phone}}</td>
                                    <td class="text-center">{{optional($record->city)->name}}</td>
                                    <td class="text-center">{{$record->blood_type}}</td>
                                    <td class="text-center">
                                        <a href="{{url(route('donations.edit',$record->id))}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>
                                    </td>
                                    <td class="text-center">
                                        <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                data-route="{{URL::route('donations.destroy',$record->id)}}"
                                                type="button" class="destroy btn btn-danger btn-xs"><i
                                                class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <p class="text-center">لا يوجد تبرعات !!</p>
                @endif
            </div>

        </div>


    </section>
@endsection