routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

// Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
//     Route::get('/', 'MainController@home');
//     Route::get('client-register', 'AuthController@register');
//     Route::get('about', 'MainController@about');
//     Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
// });
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('key:generate');
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    // return what you want
    return 'تم بنجاح';
});

Route::get('/migrate', function() {
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');

    // return what you want
    return 'تم بنجاح';
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth','Admin']],function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('categories','CategoryController');
    Route::resource('user','UserController');
    Route::get('category/{id}', 'CategoryController@SubCat')->name('categories.subcat');
    Route::get('subcat/{id}', 'SubCategoryController@SubCat')->name('product.subcat');
    Route::resource('subcategory','SubCategoryController');
    Route::resource('product','ProductController');
    Route::resource('mail','MailController');
    Route::resource('slider','ImageController');
    
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Model\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{
    public function changePassword()
    {
        return view('users.reset-password');
    }

    public function changePasswordSave(Request $request)
    {
        $messages = [
            'old-password' => 'required',
            'password' => 'required|confirmed',
        ];
        $rules = [
            'old-password.required' => 'كلمة السر الحالية مطلوبة',
            'password.required' => 'كلمة السر مطلوبة',
        ];
        $this->validate($request,$messages,$rules);

        $user = Auth::user();

        if (Hash::check($request->input('old-password'), $user->password)) {
            // The passwords match...
            $user->password = bcrypt($request->input('password'));
            $user->save();
            flash()->success('تم تحديث كلمة المرور');
            return view('users.reset-password');
        }else{
            flash()->error('كلمة المرور غير صحيحة');
            return view('users.reset-password');
        }

    }

    public function index()
    {

        $users = User::paginate(10);

        return view('users.index',compact('users'));
    }

    public function create(User $model)
    {
        return view('users.create',compact('model'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
//        dd();
        $this->validate($request, [
            'name' => 'required',
            'phone' => 'required|unique:users|digits:11',
            'password' => 'required|confirmed',
            'email' => 'email|unique:users|',//required
            'type' => 'required'
            // 'roles_list'  => 'required'
        ]);
        $request->merge(['password' => bcrypt($request->password)]);
        $user = User::create($request->except('roles_list'));
        // $user->roles()->attach($request->input('roles_list'));
        $user->api_token = str_random(60);
        $user->save();
        flash()->success('تم إضافة المستخدم بنجاح');
        return redirect(route('user.index'));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $model = User::findOrFail($id);
        return view('users.edit',compact('model'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request , $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'phone' => 'required|unique:users,phone,'.$id.'|digits:11',
            'password' => 'sometimes|nullable|confirmed',
            'email' => 'email|unique:users,email,'.$id,
            'type' => 'required'

        ]);
        $user = User::findOrFail($id);

        // $user->roles()->sync((array) $request->input('roles_list'));
        if (request()->filled('password')) {
            $password = bcrypt($request->password);
        }else{
            $password = $user->password;
        }
        $update = $user->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'type' => $request->type,
            'password' => $password,
            'email' => $request->email,
        ]);

        flash()->success('تم تعديل بيانات المستخدم بنجاح.');
        return redirect(route('user.index'));

    }

    public function destroy($id)
    {
        $record = User::findOrFail($id);

        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        $record->delete();
        return response()->json([
            'status'  => 1,
            'message' => 'تم الحذف بنجاح',
            'id'      => $id
        ]);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@section('page_title')
    Users
@endsection
@section('small_title')
    Add
@endsection
@section('content')
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="panel-title">
                        {!! Form::model($model,[
                            'action'=>'UserController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST'
                            ])!!}
                </div>
            </div>
            <div class="panel-body">
                    @include('users.form')
            </div>
            <div class="panel-footer">
                    <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                        {!! Form::close()!!}
                </div>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('page_title')
    Users
@endsection
@section('small_title')
    Edit
@endsection
@section('content')
<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                            {!! Form::model($model,[
                                'action'=>['UserController@update',$model->id],
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT'
                                ])!!}
                    </div>
                </div>
                <div class="panel-body">
                        @include('users.form')
                </div>
                <div class="panel-footer">
                        <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            {!! Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    

@stop

resources/views/users/form.blade.php
@include('partials.validation_errors')
@include('flash::message')

<div class="form-group">
    <label for="name">Name</label>
    {!! Form::text('name',null,[
    'class' => 'form-control'
 ]) !!}
</div>
<div class="form-group">
    <label for="email">Email</label>
    {!! Form::text('email',null,[
    'class' => 'form-control'
 ]) !!}
</div>
<div class="form-group">
    <label for="phone">Phone</label>
    {!! Form::tel('phone',null,[
    'class' => 'form-control'
    ]) !!}
</div>

<div class="form-group">
        <label for="type">User Level</label>
        {!! Form::select('type',
        ['1' => 'User','2'=>'Supervisor','3'=>'Admin']
        ,null, ['class'=>'form-control']) !!}
</div>


<div class="form-group">
    <label for="password">Password</label>
    {!! Form::password('password',[
    'class' => 'form-control'
 ]) !!}
</div>



<div class="form-group">
    <label for="password_confirmation">Password Confirmation</label>
    {!! Form::password('password_confirmation',[
    'class' => 'form-control'
 ]) !!}
</div>
{{-- <div class="form-group">
    <label for="roles_list">رتب المستخدمين</label>
    {!! Form::select('roles_list[]',$roles,null,[
    'class' => 'form-control select2',
    'multiple' => 'multiple',
 ]) !!}
</div> --}}

resources/views/users/index.blade.php
@extends('layouts.app')
@section('page_title')
    Users
@endsection
@section('small_title')
    Index
@endsection
@section('content')

<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="{{ route('user.create')}}" >
                            <button type="button" class="btn btn-success btn-rounded w-md m-b-5">
                                <i class="fa fa-plus"></i> Add Users
                            </button>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('flash::message')
                    @if(!empty($users))
                        <div class="table-responsive">
                            <table class="table table-striped table-hover text-center">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Username</th>
                                        <th>Email</th>
                                        <th>type</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @php $count = $users->currentPage() * 1; @endphp
                                    @foreach($users as $user)
                                        <tr id="removable{{$user->id}}">
                                            <td>{{$count}}</td>
                                            <td>{{$user->name}}</td>
                                            <td>{{$user->email}}</td>
                                            <td>
                                                @if ($user->type == 3 )
                                                admin
                                                @elseif($user->type == 2 )
                                                Supervisor
                                                @elseif($user->type == 1 )
                                                Users
                                                @endif    
                                            </td>
                                            <td class="text-center"><a href="user/{{$user->id}}/edit"
                                                                        class="btn  btn-success"><i class="fa fa-edit"></i></a>
                                            </td>
                                            <td class="text-center">
                                                <button id="{{$user->id}}" data-token="{{ csrf_token() }}"
                                                        data-route="{{URL::route('user.destroy',$user->id)}}"
                                                        type="button" class="destroy btn btn-danger "><i
                                                            class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                        @php $count ++; @endphp
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif

                </div>
                <div class="panel-footer">
                    <div class="text-center">
                            {!! $users->render() !!}

                            
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/users/reset-password.blade.php
@extends('layouts.app')
@section('page_title')
    تغيير كلمة المرور
@endsection

@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                            title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                {!! Form::open([
                        'action'=>'UserController@changePasswordSave',
                'id'=>'myForm',
                'role'=>'form',
                'method'=>'POST'
                ])!!}


                @include('flash::message')
                @include('partials.validation_errors')
                {{--@include('layouts.partials.validation-errors')--}}
                {{--{!! field()->password('old-password','كلمة المرور الحالية') !!}--}}
                <div class="form-group">
                    <label class="form-control"> كلمة المرور الحالية</label>
                    <input class="form-control" type="password" name="old-password"/>
                </div>
                <div class="form-group">
                    <label class="form-control">كلمة المرور الجديدة</label>
                    <input class="form-control" type="password" name="password"/>
                </div>
                <div class="form-group">
                    <label class="form-control">تأكيد كلمة المرور الجديدة</label>
                    <input class="form-control" type="password" name="password_confirmation"/>
                </div>
                </div>

            <!-- /.box -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">حفظ</button>
                </div>
                {!! Form::close()!!}
            </div>
        </div>

    </section>
@endsection