routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

// Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
//     Route::get('/', 'MainController@home');
//     Route::get('client-register', 'AuthController@register');
//     Route::get('about', 'MainController@about');
//     Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
// });
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('key:generate');
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    // return what you want
    return 'تم بنجاح';
});

Route::get('/migrate', function() {
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');

    // return what you want
    return 'تم بنجاح';
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth','Admin']],function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('categories','CategoryController');
    Route::resource('user','UserController');
    Route::get('category/{id}', 'CategoryController@SubCat')->name('categories.subcat');
    Route::get('subcat/{id}', 'SubCategoryController@SubCat')->name('product.subcat');
    Route::resource('subcategory','SubCategoryController');
    Route::resource('product','ProductController');
    Route::resource('mail','MailController');
    Route::resource('slider','ImageController');
    
});

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Product;
use App\Model\SubCategory;
use App\Model\Category;
use App\Model\Images;
use Image;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $records = Product::paginate(10);
        return view('Product.index',compact('records'));
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Product $model)
    {
        $Categorys = Category::with('Children')->get();
        return view('Product.create',compact('model','Categorys'));
    }


    public function store(Request $request)
    {
        // dd($request);
        $rules = [
            'title' => 'required|string',
            'doscription' => 'required|string',
            'price' => 'required|numeric',
            'Wholesale_price' => 'required|numeric',
            'Special_price' => 'required|numeric',
            'sub_category_id' => 'required',
            'Hoot_deals' => 'nullable|numeric',
            
        ];
        $messages = [
            'title.required' => 'Name is required'
        ];
        $this->validate($request,$rules,$messages);
        // dd($request);
            $record = new Product;
            $record->title = $request->input('title');
            $record->doscription = $request->input('doscription');
            $record->price = $request->input('price');
            $record->Wholesale_price = $request->input('Wholesale_price');
            $record->Special_price = $request->input('Special_price');
            $record->Hoot_deals = $request->input('Hoot_deals');
            $record->sub_category_id = $request->input('sub_category_id');
            $record->save();
            
            if (request()->file('images')) {
                $Size = range(0,count($request->images)-1);
                $images = array_combine($Size, $request->images);
                for ($i=0; $i < count($images) ; $i++) { 
                    # code...
                    $avatar = $images[$i];
                    $profileImgIn = time(). $record->title.'_' . $avatar->getClientOriginalName();
                    Image::make($avatar)->resize(300, 300)->save( public_path('/uploads/products/' . $profileImgIn));
                    $Images = new Images;
                    $Images->url = $profileImgIn;
                    $Images->product_id = $record->id;
                    $Images->save();
                }
            }
        flash()->success('تــم اضــافة القسم بنجــاح');
        return redirect(route('product.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        
        $model = Product::with('Images')->findOrFail($id);
        // dd($model->doscription);
        // dd($model);
        return view('Product.show',compact('model'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Product::with('Images')->findOrFail($id);
        // $SubCategory = SubCategory::pluck('name', 'id')->toArray();
        $Categorys = Category::with('Children')->get();

        return view('Product.edit',compact('model','Categorys'));

    }


    public function update(Request $request,  $id)
    {
        $rules = [
            'title' => 'required|string',
            'doscription' => 'required|string',
            'price' => 'required|numeric',
            'Wholesale_price' => 'required|numeric',
            'Special_price' => 'required|numeric',
            'sub_category_id' => 'required',
            'Hoot_deals' => 'nullable|numeric',
        ];
        $message = [
            'title.required' => 'Name is required'
        ];
        $this->validate($request,$rules,$message);
       
        
        $delete_ids = explode(',', $request->imageIs);
        // dd($delete_ids,$request->imageIs);
        Images::destroy($delete_ids);


        // $record = new Product;
        $record = Product::findOrFail($id);

        $record->title = $request->input('title');
        $record->doscription = $request->input('doscription');
        $record->price = $request->input('price');
        $record->Wholesale_price = $request->input('Wholesale_price');
        $record->Special_price = $request->input('Special_price');
        $record->Hoot_deals = $request->input('Hoot_deals');
        $record->sub_category_id = $request->input('sub_category_id');
        
        $record->save();

        if (request()->file('images')) {
            // dd($request->images);
            $Size = range(0,count($request->images)-1);
            $images = array_combine($Size, $request->images);
            $avatars = [];
            $ts = 0;
            for ($i=0; $i < count($images) ; $i++) { 
                # code...
                $avatar = $images[$i];
                $profileImgIn = time(). $record->title.'_' . $avatar->getClientOriginalName();
                $avatars = $profileImgIn;
                Image::make($avatar)->resize(300, 300)->save( public_path('/uploads/products/' . $profileImgIn));
                $Images = new Images;
                $Images->url = $profileImgIn;
                $Images->product_id = $record->id;
                $Images->save();
                $ts++;
            }
        }
        // $record->update($request->all());
        flash()->success('تم التحديث بنجاح');
        return redirect(route('product.index'));
    }

    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Product::find($id);
        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        $record->delete();
        return response()->json([
                'status'  => 1,
                'message' => 'تم الحذف بنجاح',
                'id'      => $id
            ]);
    }

}

resources/views/Product/create.blade.php
@extends('layouts.app')
@section('page_title')
    Product
@endsection
@section('small_title')
    Add
@endsection

@section('scripts')
<script src="{{asset('plugins/ezdz/jquery.ezdz.js')}}"></script>
<script>
        $(function () {
            function readURL(input,num) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                console.log(num);
    
                reader.onload = function(e) {
                    $('#blah-'+num).attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]);
            }
            }
    
            $(".imgInp").change(function() {
                var num =$(this).attr('num');
                readURL(this,num);
            });
    
            $(document).on('click','.box-image label span',function(){
                // console.log($(this).attr('num'));
                var reader = new FileReader();
                var num = $(this).attr('num');
                $('#blah-'+num).attr('src', "https://screenshotlayer.com/images/assets/placeholder.png");
                $('#imgInp-'+num).val(''); 
            });
    

        // CKEDITOR.replace( 'description' );
        // CKEDITOR.replace( 'description1' );
       
    });
    
    </script>
    <script src="//cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>
    
    <script>
        CKEDITOR.replace( 'doscription' );
            // $('textarea').ckeditor();
            // $('.textarea').ckeditor(); // if class is prefered.
        </script>
    @endsection
    
    @section('stylesheet')
    <link href="{{asset('plugins/ezdz/jquery.ezdz.css')}}" rel="stylesheet" type="text/css"/>
    <style>
        .blah{
            height: 200px;
            cursor:pointer;
            max-width: 100%;
            width: 100%;
            
        }
    
        .imgInp{
            display: none !important;
        }
        .imgInp::after{
            content: '';
            height: 100px;
            width: 100px;
            background-color: black
        }
    .wrapper-all-images {
        display: flex;
        flex-wrap: wrap;
        border: 4px solid #ddd;
        padding: 15px;
    }
    .wrapper-all-images .box-image {
        flex: 25%;
        max-width: 25%;
        height: 200px;
        padding: 10px;
    }
    
    .wrapper-all-images .box-image label{
        position: relative;
    }
    
    .wrapper-all-images .box-image label span{
        position: absolute;
        right: 10px;
        font-size: 20px;
        color: #fff;
        background-color: rgba(0, 0, 0, .3);
        padding: 2px;
        cursor: pointer;
    }

    @media (max-width: 992px) {
        .wrapper-all-images .box-image {
            flex: 50%;
            max-width: 50%;
            height: 150px;
        }
    }
    </style>
@endsection
@section('content')
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="panel-title">
                        {!! Form::model($model,[
                            'action' => 'ProductController@store',
                            'files' => true,

                            ]) !!}
                </div>
            </div>
            <div class="panel-body">
                    @include('Product.form')
                    <label for="sub_category_id">Category</label>
                    <div class="form-group">
                        {{-- <label for=""></label> --}}
                        <select class="form-control" name="sub_category_id" id="sub_category_id">
                            <option selected>Select one</option>
                            @foreach ($Categorys as $Category)
                            <option value="" disabled>{{$Category->name}}</option>
                                @foreach ($Category->Children as $Children)
                                    <option value="{{$Children->id}}">{{$Category->name}} - {{$Children->name}}</option>
                                @endforeach
                            @endforeach
                            <option value=""></option>
                        </select>
                    </div>
                    <div class="form-group">
                            {!! Form::label('images', 'Product gallery') !!}

                        <div class="wrapper-all-images">
                    @for($i = 0; $i < 12; $i++)
                    <div class="box-image">
                        <label for="imgInp-{{$i}}"><span num="{{$i}}">X</span><img class="blah" id="blah-{{$i}}" src="https://screenshotlayer.com/images/assets/placeholder.png" num="{{$i}}" alt="your image" /></label>
                        <input type='file'id="imgInp-{{$i}}"   name="images[]" class="imgInp" num="{{$i}}" />
                    </div>
                    @endfor
            </div>
            <div class="panel-footer">
                    <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                        {!! Form::close()!!}
                </div>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/Product/edit.blade.php
@extends('layouts.app')
@section('page_title')
Product
@endsection
@section('small_title')
Edit
@endsection
@section('scripts')
<script src="{{asset('plugins/ezdz/jquery.ezdz.js')}}"></script>

<script>
    $(function () {
        var image_ids = [];
        function readURL(input,num) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            console.log(num);

            reader.onload = function(e) {
                $('#blah-'+num).attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
        }

        $(".imgInp").change(function() {
            var num =$(this).attr('num');
            readURL(this,num);
        });

        $(document).on('click','.box-image label span',function(){
            // console.log($(this).attr('num'));
            var reader = new FileReader();
            var num = $(this).attr('num');
            var image_id = $(this).attr('image_id');
            image_ids.push( image_id );
            $('#imageIs').val(image_ids);
            console.log(num);
            $('#blah-'+num).attr('src', "https://screenshotlayer.com/images/assets/placeholder.png");
            $('#imgInp-'+num).val(''); 
            reader.readAsDataURL(input.files[0]);
        });

        
    // CKEDITOR.replace( 'description' );
    // CKEDITOR.replace( 'description1' );
   
});

</script>

<script src="//cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>
    
<script>
    CKEDITOR.replace( 'doscription' );
        // $('textarea').ckeditor();
        // $('.textarea').ckeditor(); // if class is prefered.
    </script>
@endsection

@section('stylesheet')
<link href="{{asset('plugins/ezdz/jquery.ezdz.css')}}" rel="stylesheet" type="text/css"/>
<style>
    .blah{
        height: 200px;
        cursor:pointer;
        max-width: 100%;
        width: 100%;
        
    }

    .imgInp{
        display: none !important;
    }
    .imgInp::after{
        content: '';
        height: 100px;
        width: 100px;
        background-color: black
    }
.wrapper-all-images {
    display: flex;
    flex-wrap: wrap;
    border: 4px solid #ddd;
    padding: 15px;
}
.wrapper-all-images .box-image {
    flex: 25%;
    max-width: 25%;
    height: 200px;
    padding: 10px;
}

.wrapper-all-images .box-image label{
    position: relative;
}

.wrapper-all-images .box-image label span{
    position: absolute;
    right: 10px;
    font-size: 20px;
    color: #fff;
    background-color: rgba(0, 0, 0, .3);
    padding: 2px;
    cursor: pointer;
}
.wrapper-all-images .box-image .ezdz-dropzone > div {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    font: bold 20px arial;
    padding: 5px;
}
@media (max-width: 992px) {
    .wrapper-all-images .box-image {
        flex: 50%;
        max-width: 50%;
        height: 150px;
    }
}
</style>
@endsection
@section('content')
<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                            {!! Form::model($model,[
                                'action'=>['ProductController@update',$model->id],
                                'files' => true,
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT'
                                ])!!}
                    </div>
                </div>
                <div class="panel-body">
                        @include('Product.form')
                        <label for="sub_category_id">Category</label>
                        <div class="form-group">
                            {{-- <label for=""></label> --}}
                            <select class="form-control" name="sub_category_id" id="sub_category_id">
                                <option selected>Select one</option>
                                @foreach ($Categorys as $Category)
                                <option value="" disabled>{{$Category->name}}</option>
                                    @foreach ($Category->Children as $Children)
                                        <option value="{{$Children->id}}" @if($model->sub_category_id == $Children->id) selected @endif>{{$Category->name}} - {{$Children->name}}</option>
                                    @endforeach
                                @endforeach
                                <option value=""></option>
                            </select>
                        </div>
                        <div class="form-group">
                            {{-- <label for="Parent">Category</label> --}}

                            <div class="form-group">
                                {!! Form::label('images', 'Product gallery') !!}
                                <input type="hidden" id="imageIs" name="imageIs">
                                {{-- {!! Form::file('image', ['accept' => '.jpeg, .png, .jpg, .svg']) !!} --}}

                                <div class="wrapper-all-images">
                                    @if (count($model->Images) > 0)
                                        
                                        @for($i = 0; $i < count($model->Images); $i++)
                                            <div class="box-image">
                                                <label for="imgInp-{{$i}}"><span image_id="{{$model->Images[$i]->id}}" num="{{$i}}">X</span><img class="blah" id="blah-{{$i}}" src="{{asset('uploads/products/'.$model->Images[$i]->url)}}" num="{{$i}}" alt="your image" /></label>
                                                <input type='file'id="imgInp-{{$i}}"   name="images[]" class="imgInp" num="{{$i}}" />
                                            </div>
                                        @endfor
                                        @for($i = count($model->Images); $i < 12; $i++)
                                            <div class="box-image">
                                                <label for="imgInp-{{$i}}"><span num="{{$i}}">X</span><img class="blah" id="blah-{{$i}}" src="https://screenshotlayer.com/images/assets/placeholder.png" num="{{$i}}" alt="your image" /></label>
                                                <input type='file'id="imgInp-{{$i}}"   name="images[]" class="imgInp" num="{{$i}}" />
                                            </div>
                                        @endfor
                                    @else
                                        @for($i = 0; $i < 12; $i++)
                                            <div class="box-image">
                                                <label for="imgInp-{{$i}}"><span num="{{$i}}">X</span><img class="blah" id="blah-{{$i}}" src="https://screenshotlayer.com/images/assets/placeholder.png" num="{{$i}}" alt="your image" /></label>
                                                <input type='file'id="imgInp-{{$i}}"   name="images[]" class="imgInp" num="{{$i}}" />
                                            </div>
                                        @endfor
                                    @endif

                                </div>
                            </div>

                            {{-- {!! Form::file('images[]',null,[
                            'class' => 'form-control',
                            'multiple' => 'multiple'
                            ]) !!} --}}
                        </div>
                </div>
                <div class="panel-footer">
                        <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            {!! Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    

@stop

resources/views/Product/form.blade.php
@include('partials.validation_errors')
@include('flash::message')

<div class="form-group">
    <label for="title">title</label>
    {!! Form::text('title',null,[
    'class' => 'form-control'
 ]) !!}
</div>


<div class="form-group">
    <label for="description">description</label>
    {!! Form::textarea('doscription',null,[
        'class' => 'form-control'
    ]) !!}
</div>


<div class="form-group">
    <label for="price">price</label>
    {!! Form::number('price',null,[
        'class' => 'form-control',
        'min' => '0',
    ]) !!}
</div>
<div class="form-group">
    <label for="Wholesale_price">Wholesale price</label>
    {!! Form::number('Wholesale_price',null,[
        'class' => 'form-control',
        'min' => '0',
    ]) !!}
</div>
<div class="form-group">
    <label for="Special_price">Special price</label>
    {!! Form::number('Special_price',null,[
        'class' => 'form-control',
        'min' => '0',
    ]) !!}
</div>

<div class="form-group">
    <label for="Hoot_deals">Hoot deals</label>
    {!! Form::number('Hoot_deals',null,[
        'class' => 'form-control',
        'min' => '0',
    ]) !!}
</div>

{{-- <div class="form-group"> --}}

    {{-- {!! Form::select('sub_category_id',$SubCategory,null,[
    'class' => 'form-control',
    'placeholder' => 'select Parent or leave it',
 ]) !!} --}}
{{-- </div> --}}

resources/views/Product/index.blade.php
@extends('layouts.app')
@section('page_title')
    Product
@endsection
@section('small_title')
    Index
@endsection
@section('content')

<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="{{ route('product.create')}}" >
                            <button type="button" class="btn btn-success btn-rounded w-md m-b-5">
                                <i class="fa fa-plus"></i> Add New Product
                            </button>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('flash::message')
                    @if(!empty($records))
                        <div class="table-responsive">
                            <table class="table table-striped table-hover text-center">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Wholesale Price</th>
                                        <th>Special Price</th>
                                        <th>Category</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @php if($records->currentPage() == 1 ){
                                                $count = $records->currentPage() * 1;
                                            }else{
                                                $count = $records->currentPage() * 10 - 9;
                                            }
                                        @endphp
                                    @foreach($records as $record)
                                        <tr id="removable{{$record->id}}">
                                            <td>{{$count}}</td>
                                            <td><a href="{{ route('product.show' ,$record->id )}}">{{$record->title}}</a></td>
                                            <td>{{$record->price}}</td>
                                            <td>{{$record->Wholesale_price}}</td>
                                            <td>{{$record->Special_price}}</td>
                                            <td>{{$record->Category->name}}</td>
                                            <td class="text-center"><a href="{{ route('product.edit' ,$record->id )}}"
                                                                        class="btn  btn-success"><i class="fa fa-edit"></i></a>
                                            </td>
                                            <td class="text-center">
                                                <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                        data-route="{{URL::route('product.destroy',$record->id)}}"
                                                        type="button" class="destroy btn btn-danger "><i
                                                            class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                        @php $count ++; @endphp
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif

                </div>
                <div class="panel-footer">
                    <div class="text-center">
                            {!! $records->render() !!}

                            
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/Product/show.blade.php
@extends('layouts.app')
@section('page_title')
    Product
@endsection
@section('small_title')
    {{$model->title}}
@endsection

@section('content')
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="panel-title">
 
                </div>
            </div>
            <div class="panel-body">
            <h1>Product Name : {{$model->title}}</h1>
            <p>Product description : </p>
            <br>
            {!!$model->doscription!!}




            @if($model->price > 0 )
            <h2>price :{{$model->price}}</h2>
            @endif
            @if($model->Wholesale_price > 0 )
            <h2>Wholesale Price :{{$model->Wholesale_price}}</h2>
            @endif
            @if($model->Hoot_deals > 0 )
            <h2>Hoot Deals :{{$model->Hoot_deals}}</h2>
            @endif
            @if($model->Special_price > 0 )
            <h2>Special Price :{{$model->Special_price}}</h2>
            @endif
            <h2>Sub Category :{{$model->Category->name}}</h2>
            <h2>Category :{{$model->Category->parent->name}}</h2>
             @if(count($model->Images) > 0)
             @foreach ($model->Images as $Image)
                 
                <div class="col-md-4">
                    <img src="{{asset('uploads/products/'.$Image->url)}}" class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="">
                </div>
            @endforeach
             @endif
            </div>
            <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
</div>

@stop