routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
    Route::get('/', 'MainController@home');
    Route::get('client-register', 'AuthController@register');
    Route::get('about', 'MainController@about');
    Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth'] , 'prefix'=>'admin'],function() {
    Route::get('home', 'HomeController@index');
    Route::resource('governorates','GovernorateController');
    Route::resource('cities','CityController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('donations','DonationController');
    Route::resource('contacts','ContactController');
    Route::resource('reports','ReportController');
    Route::get('clients-activate/{id}','ClientController@activate')->name('clients.activate');
    Route::get('clients-deactivate/{id}','ClientController@deactivate')->name('clients.deactivate');
    Route::get('clients-toggle-activation/{id}','ClientController@toggleActivation')->name('clients.toggle-activation');
    Route::resource('clients','ClientController');
    Route::resource('settings','SettingController');
    Route::resource('user','UserController');
    Route::resource('role','RoleController');
    // User reset password
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');

});

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\Governorate;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $records = City::paginate(20);
        return view('cities.index', compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $governorates = Governorate::pluck('name', 'id')->toArray();
        return view('cities.create', compact('governorates'));
    }


    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'governorate_id' => 'required'
        ];
        $message = [
            'name.required' => 'الاسم مطلوب',
            'governorate_id.required' => 'المحافظة مطلوبة ',
        ];
        $this->validate($request, $rules, $message);
        $record = City::create($request->all());
        flash()->success('تمت إضافة المدينة بنجاح');
        return redirect(route('cities.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = City::findOrFail($id);
        return view('cities.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $record = City::findOrFail($id);
            $record->update($request->all());
        flash()->success('لقـــد تـــــــم التحــديــــــــث بنــجـــــــاح');
        return redirect(route('cities.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = City::find($id);
        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        $record->delete();
        return response()->json([
                'status'  => 1,
                'message' => 'تم الحذف بنجاح',
                'id'      => $id
            ]);
    }

}

resources/views/cities/create.blade.php
@extends('layouts.app')
@inject('model','App\Models\Governorate')
@section('page_title')
    إضافة مدينة
@endsection

@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                {!! Form::model($model,[
                'action' => 'CityController@store'
                ]) !!}
                @include('partials.validation_errors')
                <div class="form-group">
                    <label for="name">الإسم</label>
                    {!! Form::text('name',null,[
                    'class' => 'form-control'
                 ]) !!}
                </div>
                <div class="form-group">
                    {!! Form::select('governorate_id',$governorates,null,[
                    'placeholder' => 'اختر المحافظة',
                     'class' => 'form-control'
                     ])!!}
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit"> حفظ</button>
                </div>

                {!! Form::close () !!}
            </div>

        </div>
    </section>
@endsection

resources/views/cities/edit.blade.php
@extends('layouts.app')
@section('page_title')
    تعديل المدينة
@endsection
@inject('governorates','App\Models\Governorate')
@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                {!! Form::model($model,[
                'action' => ['CityController@update',$model->id],
                'method' => 'put'
                ]) !!}
                @include('flash::message')
                @include('partials.validation_errors')
                <div class="form-group">
                    <label for="name">الإسم</label>
                    {!! Form::text('name',null,[
                    'class' => 'form-control'
                 ]) !!}
                </div>

                <div class="form-group">
                    <label for="name">المحافظة</label>
                    {!! Form::select('governorate_id',$governorates->pluck('name','id')->toArray(),null,[
                    'class' => 'form-control'
                 ]) !!}
                </div>

                <div class="form-group">
                    <button class="btn btn-primary" type="submit">تعديل</button>
                </div>

                {!! Form::close () !!}
            </div>

        </div>
    </section>
@endsection

resources/views/cities/from.blade.php
<div class="form-group">
    <label for="name">Name</label>
    {!! Form::text('name',null,[
    'class' => 'form-control'
 ]) !!}


</div>
<div class="form-group">
    <button class="btn btn-primary" type="submit"> Create</button>
</div>

resources/views/cities/index.blade.php
@extends('layouts.app')
@section('page_title')
    المدن
@endsection

@section('content')


    <section class="content">

        <div class="box">
            <div class="box-header with-border">


                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <a href="{{url(route('cities.create'))}}" class="btn btn-primary"><i class="fa fa-plus"> </i>أضف مدينة</a>
                @include('flash::message')
                @if(count($records))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th class="text-center">المدينة</th>
                                <th class="text-center">المحافظة</th>
                                <th class="text-center">تعديل</th>
                                <th class="text-center">حذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr id="removable{{$record->id}}">
                                    <td>{{$loop->iteration}}</td>
                                    <td class="text-center">{{$record->name}}</td>
                                    <td class="text-center">{{$record->governorate->name}}</td>
                                    <td class="text-center">
                                        <a href="{{url(route('cities.edit',$record->id))}}" class="btn btn-success btn-xs">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                data-route="{{URL::route('cities.destroy',$record->id)}}"
                                                type="button" class="destroy btn btn-danger btn-xs"><i
                                                class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-danger" role="alert">
                       لا توجد بيانات
                    </div>
                @endif
            </div>

        </div>


    </section>
@endsection