routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
    Route::get('/', 'MainController@home');
    Route::get('client-register', 'AuthController@register');
    Route::get('about', 'MainController@about');
    Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth'] , 'prefix'=>'admin'],function() {
    Route::get('home', 'HomeController@index');
    Route::resource('governorates','GovernorateController');
    Route::resource('cities','CityController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('donations','DonationController');
    Route::resource('contacts','ContactController');
    Route::resource('reports','ReportController');
    Route::get('clients-activate/{id}','ClientController@activate')->name('clients.activate');
    Route::get('clients-deactivate/{id}','ClientController@deactivate')->name('clients.deactivate');
    Route::get('clients-toggle-activation/{id}','ClientController@toggleActivation')->name('clients.toggle-activation');
    Route::resource('clients','ClientController');
    Route::resource('settings','SettingController');
    Route::resource('user','UserController');
    Route::resource('role','RoleController');
    // User reset password
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');

});

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $records = Client::where(function ($query) use($request){
            if ($request->input('keyword'))
            {
                $query->where(function ($query) use($request){
                    $query->where('name','like','%'.$request->keyword.'%');
                    $query->orWhere('phone','like','%'.$request->keyword.'%');
                    $query->orWhere('email','like','%'.$request->keyword.'%');
                    $query->orWhereHas('city',function ($city) use($request){
                        $city->where('name','like','%'.$request->keyword.'%');
                    });
                });
            }

            if ($request->input('blood_type_id'))
            {
                $query->where('blood_type_id',$request->blood_type_id);
            }
        })->paginate(20);
        return view('clients.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Client::find($id);
        if (!$record) {
            return response()->json([
                    'status' => 0,
                    'message' => 'تعذر الحصول على البيانات',
                ]);
        }


        if ($record->requests()->count() || $record->contacts()->count()) {
            return response()->json([
                    'status' => 0,
                    'message' => 'يوجد عمليات مرتبطة بهذا العميل',
                ]);
        }

        $record->delete();
        return response()->json([
            'status' => 1,
            'message' => 'تم الحذف بنجاح',
            'id' => $id,
        ]);
    }

    public function activate($id)
    {

        $client = Client::findOrFail($id);
        $client->update(['is_active' => 1]);
        flash()->success('تم التفعيل');
        return back();
    }

    public function deactivate($id)
    {
        $client = Client::findOrFail($id);
        $client->update(['is_active' => 0]);
        flash()->success('تم إلغاء التفعيل');
        return back();
    }

    public function toggleActivation($id)
    {
        $client = Client::findOrFail($id);
        $msg = 'تم التفعيل';
        if ($client->is_active)
        {
            $msg = 'تم إلغاء التفعيل';
            $client->update(['is_active' => 0]);
        }else{
            $client->update(['is_active' => 1]);
        }
        flash()->success($msg);
        return back();
    }

}

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('page_title')
    العملاء
@endsection
@section('content')


    <section class="content">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">كل العملاء</h3>

            </div>
            <div class="box-body">
                <div class="filter">
                    {!! Form::open([
                        'method' => 'get'
                    ]) !!}

                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                {!! Form::text('keyword',request('keyword'),[
                                    'class' => 'form-control',
                                    'placeholder' => 'بحث بالاسم ورقم الهاتف والايميل'
                                ]) !!}
                            </div>
                        </div>
                        @inject('bloodType','App\Models\BloodType')
                        <div class="col-sm-3">
                            {!! Form::select('blood_type_id',$bloodType->pluck('name','id')->toArray(),request('blood_type_id'),[
                                    'class' => 'form-control',
                                    'placeholder' => 'بحث بفصيلة الدم'
                                ]) !!}
                        </div>
                        <div class="col-sm-3"></div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">بحث</button>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                @include('flash::message')
                @if(count($records))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الإسم</th>
                                <th>الإيميل</th>
                                <th>تاريخ الميلاد</th>
                                <th>الهاتف</th>
                                <th>فصيلة الدم</th>
                                <th>اخر تاريخ تبرع بالدم</th>
                                <th>المدينة</th>
                                <th class="text-center">تفعيل / الغاء التفعيل</th>
                                <th class="text-center">حذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr id="removable{{$record->id}}">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$record->name}}</td>
                                    <td>{{$record->email}}</td>
                                    <td>{{$record->birth_date}}</td>
                                    <td>{{$record->phone}}</td>
                                    <td class="text-center" style="direction: ltr">{{optional($record->bloodType)->name}}</td>
                                    <td>{{$record->donation_last_date}}</td>
                                    <td>{{optional($record->city)->name}}</td>
                                    <td class="text-center">
                                        @if($record->is_active)
                                            <a href="{{url(route('clients.toggle-activation',$record->id))}}" class="btn btn-danger btn-xs">إلغاء
                                                التفعيل</a>
                                        @else
                                            <a href="{{url(route('clients.toggle-activation',$record->id))}}"
                                               class="btn btn-success btn-xs">تفعيل</a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                data-route="{{URL::route('clients.destroy',$record->id)}}"
                                                type="button" class="destroy btn btn-danger btn-xs"><i
                                                    class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <p class="text-center"> لا يوجد عملاء !!</p>
                @endif
            </div>

        </div>


    </section>
@endsection