routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

// Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
//     Route::get('/', 'MainController@home');
//     Route::get('client-register', 'AuthController@register');
//     Route::get('about', 'MainController@about');
//     Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
// });
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('key:generate');
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    // return what you want
    return 'تم بنجاح';
});

Route::get('/migrate', function() {
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');

    // return what you want
    return 'تم بنجاح';
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth','Admin']],function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('categories','CategoryController');
    Route::resource('user','UserController');
    Route::get('category/{id}', 'CategoryController@SubCat')->name('categories.subcat');
    Route::get('subcat/{id}', 'SubCategoryController@SubCat')->name('product.subcat');
    Route::resource('subcategory','SubCategoryController');
    Route::resource('product','ProductController');
    Route::resource('mail','MailController');
    Route::resource('slider','ImageController');
    
});

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Model\Category;
use App\Model\SubCategory;
use App\Model\Product;
use Image;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $records = Category::paginate(10);
        return view('categories.index',compact('records'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function SubCat($id)
    {
        //
        $records = SubCategory::where('category_id' , $id)->paginate(10);
        $Category = Category::find($id);
        return view('categories.indexSub',compact('records','Category','id'));
    }

    public function SubCatEdit($id)
    {
        //
        // $records = SubCategory::where('category_id' , $id)->paginate(10);
        // $Category = Category::find($id);

        $model = SubCategory::findOrFail($id);
        $Category = Category::pluck('name', 'id')->toArray();
        return view('subcategory.edit',compact('model','Category'));
    }
    

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $model)
    {
        // $Category = Category::pluck('name', 'id')->toArray();
        return view('categories.create',compact('model'));
    }


    public function store(Request $request)
    {
        // dd($request);
        $rules = [
            'name' => 'required',
        ];
        $messages = [
            'name.required' => 'Name is required'
        ];
        $this->validate($request,$rules,$messages);

        
            $record = new Category;
            if (request()->hasFile('images')) {
                $avatar = request()->file('images')[0];
                $profileImgIn = time().'_' . $avatar->getClientOriginalName();
                Image::make($avatar)->resize(300, 300)->save( public_path('/uploads/cat/' . $profileImgIn));
                $record->image = $profileImgIn;
            }
            $record->name = $request->input('name');
            $record->save();
        flash()->success('تــم اضــافة القسم بنجــاح');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Category::findOrFail($id);
        // dd($model);
        // $Category = Category::pluck('name', 'id')->toArray();
        return view('categories.edit',compact('model'));
    }


    public function update(Request $request, $id)
    {
        $rules = [
                 'name' => 'required'
        ];
        $message = [
                  'name.required' => 'Name is required'
        ];
        $this->validate($request,$rules,$message);
        $record = Category::findOrFail($id);
        $profileImgIn = $record->image;
        // dd($request);
        if (request()->hasFile('images')) {
            # code...D
            // if($request->hasFile('input_img')) {
            $avatar = request()->file('images')[0];
            $profileImgIn = time().'_' . $avatar->getClientOriginalName();
            Image::make($avatar)->resize(300, 300)->save( public_path('/uploads/cat/' . $profileImgIn));
        } 
            $record->name = $request->input('name');
            $record->image = $profileImgIn;
            $record->save();
        // $record->update($request->all());
        flash()->success('تم التحديث بنجاح');
        return redirect(route('categories.index'));
    }

    public function updateSub(Request $request, $id)
    {
        $rules = [
                 'name' => 'required'
        ];
        $message = [
                  'name.required' => 'Name is required'
        ];
        $this->validate($request,$rules,$message);
        $record = Category::findOrFail($id);

        if (request()->filled('Parent')) {
            // dd('Parent');
            $record->delete();
            $record = new SubCategory;
            $record->name = $request->input('name');
            $record->category_id = $request->input('Parent');
            $record->save();
        }else{
            // dd('Not Parent');
            // $record = new Category;
            $record->name = $request->input('name');
            $record->save();
        }
        // $record->update($request->all());
        flash()->success('تم التحديث بنجاح');
        return redirect(route('categories.index'));
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Category::find($id);
        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }
        $SubCategory = SubCategory::where('category_id' , $id)->get();
        foreach ($SubCategory as $Sub) {
            $Product = Product::where('sub_category_id' , $Sub->id)->delete();
        }
        $SubCategory = SubCategory::where('category_id' , $id)->delete();

        $record->delete();
        return response()->json([
                'status'  => 1,
                'message' => 'تم الحذف بنجاح',
                'id'      => $id
            ]);
    }

}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('page_title')
    Sub Category
@endsection
@section('small_title')
    Add
@endsection
@section('content')
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="panel-title">
                        {!! Form::model($model,[
                            'action' => 'CategoryController@store',
                            'files' => true,
                            ]) !!}
                </div>
            </div>
            <div class="panel-body">
                    @include('categories.form')
                    <div class="form-group">
                        {!! Form::label('images', 'images') !!}

                    <div class="wrapper-all-images">
                        <div class="box-image">
                            <label for="imgInp"><span num="">X</span><img class="blah" id="blah" src="https://screenshotlayer.com/images/assets/placeholder.png" num="" alt="your image" /></label>
                            <input type='file'id="imgInp"   name="images[]" class="imgInp" num="" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                    <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                        {!! Form::close()!!}
                </div>
            </div>
        </div>
    </div>
</div>

@stop

@section('scripts')
<script src="{{asset('plugins/ezdz/jquery.ezdz.js')}}"></script>
<script>
        $(function () {
            function readURL(input,num) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                console.log(num);
    
                reader.onload = function(e) {
                    $('#blah').attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]);
            }
            }
    
            $(".imgInp").change(function() {
                var num =$(this).attr('num');
                readURL(this,num);
            });
    
            $(document).on('click','.box-image label span',function(){
                // console.log($(this).attr('num'));
                var reader = new FileReader();
                var num = $(this).attr('num');
                $('#blah').attr('src', "https://screenshotlayer.com/images/assets/placeholder.png");
                $('#imgInp').val(''); 
            });
    
            
        // CKEDITOR.replace( 'description' );
        // CKEDITOR.replace( 'description1' );
       
    });
    
    </script>
    @endsection
    
    @section('stylesheet')
    <link href="{{asset('plugins/ezdz/jquery.ezdz.css')}}" rel="stylesheet" type="text/css"/>
    <style>
        .blah{
            height: 400px;
            cursor:pointer;
            max-width: 100%;
            width: 100%;
        }
    
        .imgInp{
            display: none !important;
        }
        .imgInp::after{
            content: '';
            height: 100px;
            width: 100px;
            background-color: black
        }
    .wrapper-all-images {
        display: flex;
        flex-wrap: wrap;
        border: 4px solid #ddd;
        padding: 15px;
    }
    .wrapper-all-images .box-image {
        flex: 100%;
        width: 100%;
        height: 400px;
        padding: 10px;
    }
    
    .wrapper-all-images .box-image label{
        position: relative;
        width: 100% !important;
    }
    
    .wrapper-all-images .box-image label span{
        position: absolute;
        right: 10px;
        font-size: 20px;
        color: #fff;
        background-color: rgba(0, 0, 0, .3);
        padding: 2px;
        cursor: pointer;
    }

    @media (max-width: 992px) {
        .wrapper-all-images .box-image {
            flex: 50%;
            max-width: 50%;
            height: 150px;
        }
    }
    </style>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('page_title')
    Category
@endsection
@section('small_title')
    Edit
@endsection
@section('content')
<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                            {!! Form::model($model,[
                                'action'=>['CategoryController@update',$model->id],
                                'files' => true,
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'PUT'
                                ])!!}
                    </div>
                </div>
                <div class="panel-body">
                        @include('categories.form')

                        <div class="form-group">
                            {!! Form::label('images', 'Product gallery') !!}
    
                        <div class="wrapper-all-images">
                            <div class="box-image">
                                <label for="imgInp"><span num="">X</span><img class="blah" id="blah" src="{{asset('uploads/cat/'.$model->image)}}"num="" alt="your image" /></label>
                                <input type='file'id="imgInp"   name="images[]" class="imgInp" num="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                        <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            {!! Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    

@stop

@section('scripts')
<script src="{{asset('plugins/ezdz/jquery.ezdz.js')}}"></script>
<script>
        $(function () {
            function readURL(input,num) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                console.log(num);
    
                reader.onload = function(e) {
                    $('#blah').attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]);
            }
            }
    
            $(".imgInp").change(function() {
                var num =$(this).attr('num');
                readURL(this,num);
            });
    
            $(document).on('click','.box-image label span',function(){
                // console.log($(this).attr('num'));
                var reader = new FileReader();
                var num = $(this).attr('num');
                $('#blah').attr('src', "https://screenshotlayer.com/images/assets/placeholder.png");
                $('#imgInp').val(''); 
            });
    
            
        // CKEDITOR.replace( 'description' );
        // CKEDITOR.replace( 'description1' );
       
    });
    
    </script>
    @endsection
    
    @section('stylesheet')
    <link href="{{asset('plugins/ezdz/jquery.ezdz.css')}}" rel="stylesheet" type="text/css"/>
    <style>
        .blah{
            height: 400px;
            cursor:pointer;
            max-width: 100%;
            width: 100%;
        }
    
        .imgInp{
            display: none !important;
        }
        .imgInp::after{
            content: '';
            height: 100px;
            width: 100px;
            background-color: black
        }
    .wrapper-all-images {
        display: flex;
        flex-wrap: wrap;
        border: 4px solid #ddd;
        padding: 15px;
    }
    .wrapper-all-images .box-image {
        flex: 100%;
        width: 100%;
        height: 400px;
        padding: 10px;
    }
    
    .wrapper-all-images .box-image label{
        position: relative;
        width: 100% !important;
    }
    
    .wrapper-all-images .box-image label span{
        position: absolute;
        right: 10px;
        font-size: 20px;
        color: #fff;
        background-color: rgba(0, 0, 0, .3);
        padding: 2px;
        cursor: pointer;
    }

    @media (max-width: 992px) {
        .wrapper-all-images .box-image {
            flex: 50%;
            max-width: 50%;
            height: 150px;
        }
    }
    </style>
@endsection

resources/views/categories/form.blade.php
@include('partials.validation_errors')
@include('flash::message')

<div class="form-group">
    <label for="name">Category Name</label>
    {!! Form::text('name',null,[
    'class' => 'form-control'
 ]) !!}
</div>

{{-- <div class="form-group">
    <label for="Parent">Parent To Category</label>
    {!! Form::select('Parent',$Category,null,[
    'class' => 'form-control',
    'placeholder' => 'select Parent or leave it',
 ]) !!}
</div> --}}

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('page_title')
    Category
@endsection
@section('small_title')
    Index
@endsection
@section('content')

<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="{{ route('categories.create')}}" >
                            <button type="button" class="btn btn-success btn-rounded w-md m-b-5">
                                <i class="fa fa-plus"></i> Add Category
                            </button>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('flash::message')
                    @if(!empty($records))
                        <div class="table-responsive">
                            <table class="table table-striped table-hover text-center">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        
                                        <th>Name</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @php $count = $records->currentPage() * 1; @endphp
                                    @foreach($records as $record)
                                        <tr id="removable{{$record->id}}">
                                            <td>{{$count}}</td>
                                            <td><a href="{{ route('categories.subcat' ,$record->id )}}">{{$record->name}}</a></td>
                                            <td class="text-center"><a href="{{ route('categories.edit' ,$record->id )}}"
                                                                        class="btn  btn-success"><i class="fa fa-edit"></i></a>
                                            </td>
                                            <td class="text-center">
                                                <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                        data-route="{{URL::route('categories.destroy',$record->id)}}"
                                                        type="button" class="destroy btn btn-danger "><i
                                                            class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                        @php $count ++; @endphp
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif

                </div>
                <div class="panel-footer">
                    <div class="text-center">
                            {!! $records->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/categories/indexSub.blade.php
@extends('layouts.app')
@section('page_title')
    Sub Category
@endsection
@section('small_title')
    {{$Category->name}}
@endsection
@section('content')

<div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="{{ route('subcategory.create')}}?id={{$id}}" >
                            <button type="button" class="btn btn-success btn-rounded w-md m-b-5">
                                <i class="fa fa-plus"></i> Add Sub Category
                            </button>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    @include('flash::message')
                    @if(!empty($records))
                        <div class="table-responsive">
                            <table class="table table-striped table-hover text-center">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @php $count = $records->currentPage() * 1; @endphp
                                    @foreach($records as $record)
                                        <tr id="removable{{$record->id}}">
                                            <td>{{$count}}</td>
                                            <td><a href="{{ route('product.subcat' ,$record->id )}}">{{$record->name}}</a></td>
                                            <td class="text-center"><a href="{{ route('subcategory.edit' ,$record->id )}}"
                                                                        class="btn  btn-success"><i class="fa fa-edit"></i></a>
                                            </td>
                                            <td class="text-center">
                                                <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                        data-route="{{URL::route('subcategory.destroy',$record->id)}}"
                                                        type="button" class="destroy btn btn-danger "><i
                                                            class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                        @php $count ++; @endphp
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif

                </div>
                <div class="panel-footer">
                    <div class="text-center">
                            {!! $records->render() !!}

                            
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/categories/reset-password.blade.php
@extends('layouts.app')
@section('page_title')
    تغيير كلمة المرور
@endsection

@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                            title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                {!! Form::open([
                        'action'=>'UserController@changePasswordSave',
                'id'=>'myForm',
                'role'=>'form',
                'method'=>'POST'
                ])!!}


                @include('flash::message')
                @include('partials.validation_errors')
                {{--@include('layouts.partials.validation-errors')--}}
                {{--{!! field()->password('old-password','كلمة المرور الحالية') !!}--}}
                <div class="form-group">
                    <label class="form-control"> كلمة المرور الحالية</label>
                    <input class="form-control" type="password" name="old-password"/>
                </div>
                <div class="form-group">
                    <label class="form-control">كلمة المرور الجديدة</label>
                    <input class="form-control" type="password" name="password"/>
                </div>
                <div class="form-group">
                    <label class="form-control">تأكيد كلمة المرور الجديدة</label>
                    <input class="form-control" type="password" name="password_confirmation"/>
                </div>
                </div>

            <!-- /.box -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">حفظ</button>
                </div>
                {!! Form::close()!!}
            </div>
        </div>

    </section>
@endsection