routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 *
 * todo install entrust package
 * todo create roles module
 * todo create users module
 * todo create permissions module
 * todo apply permissions to project actions
 * user m-to-m  roles
 * roles  m-to-m  permissions
 * // spatie users m-to-m  permissions
 *
 */

Route::group(['namespace' => 'Front'],function (){//,'middleware' => 'auth:client-web'
    Route::get('/', 'MainController@home');
    Route::get('client-register', 'AuthController@register');
    Route::get('about', 'MainController@about');
    Route::post('toggle-favourite', 'MainController@toggleFavourite')->name('toggle-favourite');
});

Auth::routes();
//Admin panel
Route::group(['middleware'=>['auth'] , 'prefix'=>'admin'],function() {
    Route::get('home', 'HomeController@index');
    Route::resource('governorates','GovernorateController');
    Route::resource('cities','CityController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('donations','DonationController');
    Route::resource('contacts','ContactController');
    Route::resource('reports','ReportController');
    Route::get('clients-activate/{id}','ClientController@activate')->name('clients.activate');
    Route::get('clients-deactivate/{id}','ClientController@deactivate')->name('clients.deactivate');
    Route::get('clients-toggle-activation/{id}','ClientController@toggleActivation')->name('clients.toggle-activation');
    Route::resource('clients','ClientController');
    Route::resource('settings','SettingController');
    Route::resource('user','UserController');
    Route::resource('role','RoleController');
    // User reset password
    Route::get('user/change-password','UserController@changePassword');
    Route::post('user/change-password','UserController@changePasswordSave');

});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $records = Role::paginate(10);
        return view('roles.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create');
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|unique:roles,name',
            'display_name' => 'required',
            'permissions_list' => 'required|array'
        ];
        $messages = [
            'name.required' => 'Name is required',
            'display_name.required' => 'Display Name is required',
            'permissions_list.required' => 'Permissions is required'
        ];
        $this->validate($request,$rules,$messages);
        $record = Role::create($request->all());
        $record->permissions()->attach($request->permissions_list);
        flash()->success('تــم اضــافة الرتبة بنجــاح');
        return redirect(route('role.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Role::findOrFail($id);
        return view('roles.edit',compact('model'));
    }


    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|unique:roles,name,'.$id,
            'display_name' => 'required',
            'permissions_list' => 'required|array'
        ];
        $messages = [
            'name.required' => 'Name is required',
            'display_name.required' => 'Display Name is required',
            'permissions_list.required' => 'Permissions is required'
        ];
        $this->validate($request,$rules,$messages);
        $record = Role::findOrFail($id);
        $record->update($request->all());
        $record->permissions()->sync($request->permissions_list);
        flash()->success('تم التحديث بنجاح');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Role::find($id);
        if (!$record) {
            return response()->json([
                'status'  => 0,
                'message' => 'تعذر الحصول على البيانات'
            ]);
        }

        $record->delete();
        return response()->json([
                'status'  => 1,
                'message' => 'تم الحذف بنجاح',
                'id'      => $id
            ]);
    }

}

resources/views/roles/create.blade.php
@extends('layouts.app')
@inject('model','App\Models\Role')
@section('page_title')
   إضافة رتبة
@endsection

@section('content')


    <section class="content">

        <div class="box">

            <div class="box-header with-border">

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                {!! Form::model($model,[
                'action' => 'RoleController@store'
                ]) !!}
                @include('partials.validation_errors')
                @include('roles.form')
                {!! Form::close () !!}
            </div>

        </div>
    </section>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('page_title')
   تعديل رتبة
@endsection

@section('content')


    <section class="content">

        <div class="box">
            <div class="box-body">
                {!! Form::model($model,[
                'action' => ['RoleController@update',$model->id],
                'method' => 'put'
                ]) !!}
                @include('flash::message')
                @include('partials.validation_errors')
                @include('roles.form')

                {!! Form::close () !!}
            </div>

        </div>
    </section>
@endsection

resources/views/roles/form.blade.php
@inject('perm','App\Models\Permission')
<div class="form-group">
    <label for="name">الاسم</label>
    {!! Form::text('name',null,[
    'class' => 'form-control'
 ]) !!}
</div>
<div class="form-group">
    <label for="display_name">الاسم المعروض</label>
    {!! Form::text('display_name',null,[
    'class' => 'form-control'
 ]) !!}
</div>
<div class="form-group">
    <label for="description">الوصف</label>
    {!! Form::textarea('description',null,[
    'class' => 'form-control'
 ]) !!}
</div>
<div class="form-group">
    <label for="name">الصلاحيات</label><br>
    <input id="select-all" type="checkbox"><label for='select-all'>اختيار الكل</label>
    <br>
    <div class="row">
        @foreach($perm->all() as $permission)
            <div class="col-sm-3">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="permissions_list[]" value="{{$permission->id}}"
                        @if($model->hasPermission($permission->name))
                            checked
                        @endif
                        >
                        {{$permission->display_name}}
                    </label>
                </div>
            </div>
        @endforeach
    </div>
</div>
<div class="form-group">
    <button class="btn btn-primary" type="submit"> حفظ</button>
</div>


@push('scripts')
    <script>
        $("#select-all").click(function(){
            $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
        });

    </script>
@endpush

resources/views/roles/index.blade.php
@extends('layouts.app')
@section('page_title')
    رتب المستخدمين
@endsection

@section('content')


    <section class="content">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">كل الرتب</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <a href="{{url(route('role.create'))}}" class="btn btn-primary"><i class="fa fa-plus"></i> أضف رتبة</a>
                @include('flash::message')
                @if(count($records))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th> الاسم المعروض</th>
                                <th class="text-center">تعديل</th>
                                <th class="text-center">حذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr id="removable{{$record->id}}">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$record->name}}</td>
                                    <td>{{$record->display_name}}</td>
                                    <td class="text-center">
                                        <a href="{{url(route('role.edit',$record->id))}}" class="btn btn-success btn-xs">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <button id="{{$record->id}}" data-token="{{ csrf_token() }}"
                                                data-route="{{URL::route('role.destroy',$record->id)}}"
                                                type="button" class="destroy btn btn-danger btn-xs"><i
                                                class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-danger" role="alert">
                        لا يوجد بيانات
                    </div>
                @endif
            </div>

        </div>


    </section>
@endsection